services: docker
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
- docker build -t test-image .
- docker run --name test-container -d test-image
- docker exec --tty test-container env TERM=xterm molecule -v
notifications:
  email:
    - sham1316@gmail.com